"""Sync all the survey tables with sqlalchemy models

Revision ID: 6a98a185f3bb
Revises: f7ad6f38a6f6
Create Date: 2026-01-05 23:17:51.421453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a98a185f3bb'
down_revision: str | None = 'f7ad6f38a6f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'survey_constructs',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_nullable=False,
    )
    op.alter_column(
        'survey_constructs',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'survey_constructs',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    )
    op.drop_constraint(op.f('fk_survey_constructs_created_by_id'), 'survey_constructs', type_='foreignkey')
    op.drop_column('survey_constructs', 'created_by_id')

    op.alter_column('survey_items', 'text', existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.alter_column('survey_items', 'notes', existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    op.alter_column(
        'survey_items',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_nullable=False,
    )
    op.alter_column(
        'survey_items',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'survey_items',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    )
    op.alter_column(
        'survey_items', 'enabled', existing_type=sa.BOOLEAN(), server_default=sa.text('TRUE'), existing_nullable=False
    )
    op.drop_constraint(op.f('fk_survey_items_created_by_id'), 'survey_items', type_='foreignkey')
    op.drop_column('survey_items', 'created_by_id')

    op.alter_column(
        'survey_scale_levels',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_nullable=False,
    )
    op.alter_column(
        'survey_scale_levels',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'survey_scale_levels',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    )
    op.alter_column(
        'survey_scale_levels',
        'enabled',
        existing_type=sa.BOOLEAN(),
        server_default=sa.text('TRUE'),
        existing_nullable=False,
    )
    op.drop_constraint(op.f('fk_survey_scale_levels_created_by_id'), 'survey_scale_levels', type_='foreignkey')
    op.drop_column('survey_scale_levels', 'created_by_id')

    op.alter_column(
        'survey_scales',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_nullable=False,
    )
    op.alter_column(
        'survey_scales',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'survey_scales',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    )
    op.alter_column(
        'survey_scales', 'enabled', existing_type=sa.BOOLEAN(), server_default=sa.text('TRUE'), existing_nullable=False
    )
    op.drop_constraint(op.f('fk_survey_scales_created_by_id'), 'survey_scales', type_='foreignkey')
    op.drop_column('survey_scales', 'date_created')
    op.drop_column('survey_scales', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_scales', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column(
        'survey_scales',
        sa.Column(
            'date_created',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f('fk_survey_scales_created_by_id'), 'survey_scales', 'users', ['created_by_id'], ['id'], ondelete='SET NULL'
    )
    op.alter_column(
        'survey_scales', 'enabled', existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        'survey_scales',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        'survey_scales',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('survey_scales', 'id', existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.add_column('survey_scale_levels', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f('fk_survey_scale_levels_created_by_id'),
        'survey_scale_levels',
        'users',
        ['created_by_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.alter_column(
        'survey_scale_levels', 'enabled', existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        'survey_scale_levels',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        'survey_scale_levels',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('survey_scale_levels', 'id', existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.add_column('survey_items', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f('fk_survey_items_created_by_id'), 'survey_items', 'users', ['created_by_id'], ['id'], ondelete='SET NULL'
    )
    op.alter_column('survey_items', 'enabled', existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
    op.alter_column(
        'survey_items',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        'survey_items',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('survey_items', 'id', existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column('survey_items', 'notes', existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column('survey_items', 'text', existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.add_column('survey_constructs', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f('fk_survey_constructs_created_by_id'),
        'survey_constructs',
        'users',
        ['created_by_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.alter_column(
        'survey_constructs',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        'survey_constructs',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('survey_constructs', 'id', existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    # ### end Alembic commands ###
