"""initial-schema

Revision ID: 9aa5451ca1ae
Revises: 
Create Date: 2026-01-16 21:30:24.756424

"""
import uuid
from collections.abc import Sequence
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aa5451ca1ae'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_shuffled_movie_lists',
    sa.Column('movie_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('subset_desc', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pre_shuffled_movie_lists'))
    )
    op.create_table('study_participant_types',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_participant_types'))
    )
    op.create_table('survey_constructs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_constructs'))
    )
    op.create_table('survey_scales',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_scales'))
    )
    op.create_table('users',
    sa.Column('auth0_sub', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_auth0_sub'), 'users', ['auth0_sub'], unique=True)
    op.create_table('studies',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_studies_created_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_studies_owner_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studies'))
    )
    op.create_table('survey_items',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survey_construct_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.ForeignKeyConstraint(['survey_construct_id'], ['survey_constructs.id'], name=op.f('fk_survey_items_survey_construct_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_items'))
    )
    op.create_table('survey_scale_levels',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('survey_scale_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.ForeignKeyConstraint(['survey_scale_id'], ['survey_scales.id'], name=op.f('fk_survey_scale_levels_survey_scale_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_scale_levels'))
    )
    op.create_table('api_keys',
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_api_keys_study_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('study_conditions',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('recommender_key', sa.String(), nullable=True),
    sa.Column('recommendation_count', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=48), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_study_conditions_study_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_conditions')),
    sa.UniqueConstraint('study_id', 'short_code', deferrable=True, initially='DEFERRED', name=op.f('uq_study_conditions_study_id_short_code'))
    )
    op.create_table('study_steps',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('survey_api_root', sa.String(), nullable=True),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_study_steps_study_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_steps')),
    sa.UniqueConstraint('study_id', 'order_position', name=op.f('uq_study_steps_study_id_order_position')),
    sa.UniqueConstraint('study_id', 'path', deferrable=True, initially='deferred', name=op.f('uq_study_steps_study_id_path'))
    )
    op.create_table('study_step_pages',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('page_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_study_step_pages_study_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_study_step_pages_study_step_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_step_pages')),
    sa.UniqueConstraint('study_step_id', 'order_position', name=op.f('uq_study_step_pages_study_step_id_order_position'))
    )
    op.create_table('study_participants',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('discarded', sa.Boolean(), nullable=False),
    sa.Column('study_participant_type_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('study_condition_id', sa.UUID(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('current_step_id', sa.UUID(), nullable=False),
    sa.Column('current_page_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_page_id'], ['study_step_pages.id'], name=op.f('fk_study_participants_current_page_id')),
    sa.ForeignKeyConstraint(['current_step_id'], ['study_steps.id'], name=op.f('fk_study_participants_current_step_id')),
    sa.ForeignKeyConstraint(['study_condition_id'], ['study_conditions.id'], name=op.f('fk_study_participants_study_condition_id')),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_study_participants_study_id')),
    sa.ForeignKeyConstraint(['study_participant_type_id'], ['study_participant_types.id'], name=op.f('fk_study_participants_study_participant_type_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_participants'))
    )
    op.create_table('study_step_page_contents',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('preamble', sa.Text(), nullable=True),
    sa.Column('study_step_page_id', sa.UUID(), nullable=False),
    sa.Column('survey_construct_id', sa.UUID(), nullable=False),
    sa.Column('survey_scale_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_study_step_page_contents_study_step_page_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_construct_id'], ['survey_constructs.id'], name=op.f('fk_study_step_page_contents_survey_construct_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_scale_id'], ['survey_scales.id'], name=op.f('fk_study_step_page_contents_survey_scale_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_step_page_id', 'survey_construct_id', 'survey_scale_id', 'id', name=op.f('pk_study_step_page_contents'))
    )
    op.create_table('feedbacks',
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=False),
    sa.Column('feedback_category', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('study_step_page_id', sa.UUID(), nullable=True),
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_feedbacks_study_id')),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_feedbacks_study_participant_id')),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_feedbacks_study_step_id')),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_feedbacks_study_step_page_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedbacks'))
    )
    op.create_table('participant_demographics',
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('age_range', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('gender_other', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('race_other', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state_region', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_demographics_study_participant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_demographics'))
    )
    op.create_table('participant_freeform_responses',
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('study_step_page_id', sa.UUID(), nullable=True),
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_participant_freeform_responses_study_id')),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_freeform_responses_study_participant_id')),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_participant_freeform_responses_study_step_id')),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_participant_freeform_responses_study_step_page_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_freeform_responses')),
    sa.UniqueConstraint('study_id', 'study_participant_id', 'context_tag', name=op.f('uq_participant_freeform_responses_study_id_study_part_8006a1'))
    )
    op.create_table('participant_interaction_logs',
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('study_step_page_id', sa.UUID(), nullable=True),
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_participant_interaction_logs_study_id')),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_interaction_logs_study_participant_id')),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_participant_interaction_logs_study_step_id')),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_participant_interaction_logs_study_step_page_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_interaction_logs')),
    sa.UniqueConstraint('study_id', 'study_participant_id', 'context_tag', name=op.f('uq_participant_interaction_logs_study_id_study_partic_6aa83f'))
    )
    op.create_table('participant_ratings',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_table_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=False),
    sa.Column('scale_max', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('study_step_page_id', sa.UUID(), nullable=True),
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_participant_ratings_study_id')),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_ratings_study_participant_id')),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_participant_ratings_study_step_id')),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_participant_ratings_study_step_page_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_ratings'))
    )
    op.create_table('participant_recommendation_contexts',
    sa.Column('recommendations_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('study_step_page_id', sa.UUID(), nullable=True),
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_participant_recommendation_contexts_study_id')),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_recommendation_contexts_study_participant_id')),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_participant_recommendation_contexts_study_step_id')),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_participant_recommendation_contexts_study_step_page_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_recommendation_contexts')),
    sa.UniqueConstraint('study_id', 'study_participant_id', 'context_tag', name=op.f('uq_participant_recommendation_contexts_study_id_study_9290cf'))
    )
    op.create_table('participant_study_interaction_responses',
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('study_step_page_id', sa.UUID(), nullable=True),
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_participant_study_interaction_responses_study_id')),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_study_interaction_responses_study_participant_id')),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_participant_study_interaction_responses_study_step_id')),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_participant_study_interaction_responses_study_step_page_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_study_interaction_responses')),
    sa.UniqueConstraint('study_id', 'study_participant_id', 'context_tag', name=op.f('uq_participant_study_interaction_responses_study_id_s_5834e0'))
    )
    op.create_table('participant_study_sessions',
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('resume_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_study_sessions_study_participant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_study_sessions'))
    )
    op.create_table('participant_survey_responses',
    sa.Column('survey_construct_id', sa.UUID(), nullable=False),
    sa.Column('survey_item_id', sa.UUID(), nullable=True),
    sa.Column('survey_scale_id', sa.UUID(), nullable=True),
    sa.Column('survey_scale_level_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('study_step_id', sa.UUID(), nullable=False),
    sa.Column('study_step_page_id', sa.UUID(), nullable=True),
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('context_tag', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('discarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_participant_survey_responses_study_id')),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_participant_survey_responses_study_participant_id')),
    sa.ForeignKeyConstraint(['study_step_id'], ['study_steps.id'], name=op.f('fk_participant_survey_responses_study_step_id')),
    sa.ForeignKeyConstraint(['study_step_page_id'], ['study_step_pages.id'], name=op.f('fk_participant_survey_responses_study_step_page_id')),
    sa.ForeignKeyConstraint(['survey_construct_id'], ['survey_constructs.id'], name=op.f('fk_participant_survey_responses_survey_construct_id')),
    sa.ForeignKeyConstraint(['survey_item_id'], ['survey_items.id'], name=op.f('fk_participant_survey_responses_survey_item_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_scale_id'], ['survey_scales.id'], name=op.f('fk_participant_survey_responses_survey_scale_id')),
    sa.ForeignKeyConstraint(['survey_scale_level_id'], ['survey_scale_levels.id'], name=op.f('fk_participant_survey_responses_survey_scale_level_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_survey_responses'))
    )
    op.create_table('study_participant_movie_sessions',
    sa.Column('study_participant_id', sa.UUID(), nullable=False),
    sa.Column('assigned_list_id', sa.UUID(), nullable=False),
    sa.Column('current_offset', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_list_id'], ['pre_shuffled_movie_lists.id'], name=op.f('fk_study_participant_movie_sessions_assigned_list_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], name=op.f('fk_study_participant_movie_sessions_study_participant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_participant_movie_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_participant_movie_sessions')
    op.drop_table('participant_survey_responses')
    op.drop_table('participant_study_sessions')
    op.drop_table('participant_study_interaction_responses')
    op.drop_table('participant_recommendation_contexts')
    op.drop_table('participant_ratings')
    op.drop_table('participant_interaction_logs')
    op.drop_table('participant_freeform_responses')
    op.drop_table('participant_demographics')
    op.drop_table('feedbacks')
    op.drop_table('study_step_page_contents')
    op.drop_table('study_participants')
    op.drop_table('study_step_pages')
    op.drop_table('study_steps')
    op.drop_table('study_conditions')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('survey_scale_levels')
    op.drop_table('survey_items')
    op.drop_table('studies')
    op.drop_index(op.f('ix_users_auth0_sub'), table_name='users')
    op.drop_table('users')
    op.drop_table('survey_scales')
    op.drop_table('survey_constructs')
    op.drop_table('study_participant_types')
    op.drop_table('pre_shuffled_movie_lists')
    # ### end Alembic commands ###
